name: Dataset order sync

on:
  schedule:
    - cron: "45 22 * * *"
  
jobs:
  rename-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rename files with commit date
        run: |
          for f in _datasets/*; do
            COMMIT_DATE=$(git log -1 --follow --diff-filter=AMCR --no-merges --date=short --format="%cd" -- "$f")
            base=$(basename "$f")
            if [[ "$base" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}_.* ]]; then
              base1="${base:11}"
            else
              base1="$base"
            fi
            echo "File: $base"
            echo "Commit date: $COMMIT_DATE"
            if [[ "$base" != ${COMMIT_DATE}_* ]]; then
              if ls _datasets/????-??-??_$base1 1>/dev/null 2>&1; then
                base1="${base1::-3}$(date '+%m%d%H%M%S').md"
              fi
              git mv "$f" "_datasets/${COMMIT_DATE}_${base1}"
              # also create redirect
              t=$(grep '^title:' "$f" | cut -d':' -f2- | xargs)
              base1="${base1::-3}"
              echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=/datasets/${COMMIT_DATE}_${base1//%/_}/\" />$t</head><body></body></html>" \ > "datasety/${base1//%/_}.html"
              git add "datasety/${base1//%/_}.html"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Rename files with commit date [skip ci]" || echo "No changes to commit"
          git push
