name: LKOD

on:
  workflow_dispatch:

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install requests

      - name: Split file by pipe character
        run: |
          set -e  # stop on error
          python3 split_by_pipe.py
      
      - name: List contents of lkod
        run: ls -l lkod || echo "lkod folder not found"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit split files
        run: |
          git add lkod/
          git commit -m "Add split files"
          git push





